all: false
pkgname: mocks
template: testify
filename: "Mock{{.InterfaceName}}.go"
formatter: goimports
force-file-write: true

packages:
  github.com/tuannm99/judge-loop/internal/port/in:
    config:
      dir: internal/port/in/mocks
    interfaces:
      EvaluationService:
      MissionService:
      ProblemService:
      ProgressService:
      RegistryService:
      ReviewService:
      SubmissionService:
      TimerService:

  github.com/tuannm99/judge-loop/internal/port/out:
    config:
      dir: internal/port/out/mocks
    interfaces:
      CodeRunner:
      EvaluationJobQueue:
      EvaluationPublisher:
      MissionRepository:
      PerformanceRepository:
      ProblemRepository:
      RegistryRepository:
      ReviewRepository:
      SessionRepository:
      SubmissionRepository:
      TestCaseRepository:
