root = "."
tmp_dir = "/tmp/air-api-server"

[build]
cmd = "go build -o /tmp/air-api-server/api-server ./cmd/api-server"
bin = "/tmp/air-api-server/api-server"
delay = 1000
exclude_dir = [".git", ".devdata", "bin", "deploy", "docs", "node_modules", "plugins", "prompts", "registry", "ui"]
include_ext = ["go", "mod", "sum"]
kill_delay = "500ms"
send_interrupt = true
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true
