root = "."
tmp_dir = "/tmp/air-judge-worker"

[build]
cmd = "go build -buildvcs=false -o /tmp/air-judge-worker/judge-worker ./cmd/judge-worker"
bin = "/tmp/air-judge-worker/judge-worker"
delay = 1000
exclude_dir = [".git", ".devdata", "bin", "deploy", "docs", "node_modules", "plugins", "prompts", "registry", "ui"]
include_ext = ["go", "mod", "sum"]
kill_delay = "500ms"
send_interrupt = true
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true
