// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/judge-loop/internal/domain"
	"github.com/tuannm99/judge-loop/internal/port/out"
)

// NewMockProblemService creates a new instance of MockProblemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProblemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProblemService {
	mock := &MockProblemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProblemService is an autogenerated mock type for the ProblemService type
type MockProblemService struct {
	mock.Mock
}

type MockProblemService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProblemService) EXPECT() *MockProblemService_Expecter {
	return &MockProblemService_Expecter{mock: &_m.Mock}
}

// ContributeProblem provides a mock function for the type MockProblemService
func (_mock *MockProblemService) ContributeProblem(ctx context.Context, manifest domain.ProblemManifest, testCases []domain.TestCase) (*domain.Problem, error) {
	ret := _mock.Called(ctx, manifest, testCases)

	if len(ret) == 0 {
		panic("no return value specified for ContributeProblem")
	}

	var r0 *domain.Problem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ProblemManifest, []domain.TestCase) (*domain.Problem, error)); ok {
		return returnFunc(ctx, manifest, testCases)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ProblemManifest, []domain.TestCase) *domain.Problem); ok {
		r0 = returnFunc(ctx, manifest, testCases)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Problem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ProblemManifest, []domain.TestCase) error); ok {
		r1 = returnFunc(ctx, manifest, testCases)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProblemService_ContributeProblem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContributeProblem'
type MockProblemService_ContributeProblem_Call struct {
	*mock.Call
}

// ContributeProblem is a helper method to define mock.On call
//   - ctx context.Context
//   - manifest domain.ProblemManifest
//   - testCases []domain.TestCase
func (_e *MockProblemService_Expecter) ContributeProblem(ctx interface{}, manifest interface{}, testCases interface{}) *MockProblemService_ContributeProblem_Call {
	return &MockProblemService_ContributeProblem_Call{Call: _e.mock.On("ContributeProblem", ctx, manifest, testCases)}
}

func (_c *MockProblemService_ContributeProblem_Call) Run(run func(ctx context.Context, manifest domain.ProblemManifest, testCases []domain.TestCase)) *MockProblemService_ContributeProblem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ProblemManifest
		if args[1] != nil {
			arg1 = args[1].(domain.ProblemManifest)
		}
		var arg2 []domain.TestCase
		if args[2] != nil {
			arg2 = args[2].([]domain.TestCase)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProblemService_ContributeProblem_Call) Return(problem *domain.Problem, err error) *MockProblemService_ContributeProblem_Call {
	_c.Call.Return(problem, err)
	return _c
}

func (_c *MockProblemService_ContributeProblem_Call) RunAndReturn(run func(ctx context.Context, manifest domain.ProblemManifest, testCases []domain.TestCase) (*domain.Problem, error)) *MockProblemService_ContributeProblem_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProblemLabel provides a mock function for the type MockProblemService
func (_mock *MockProblemService) CreateProblemLabel(ctx context.Context, kind string, slug string, name string) (*domain.ProblemLabel, error) {
	ret := _mock.Called(ctx, kind, slug, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateProblemLabel")
	}

	var r0 *domain.ProblemLabel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.ProblemLabel, error)); ok {
		return returnFunc(ctx, kind, slug, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.ProblemLabel); ok {
		r0 = returnFunc(ctx, kind, slug, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProblemLabel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, kind, slug, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProblemService_CreateProblemLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProblemLabel'
type MockProblemService_CreateProblemLabel_Call struct {
	*mock.Call
}

// CreateProblemLabel is a helper method to define mock.On call
//   - ctx context.Context
//   - kind string
//   - slug string
//   - name string
func (_e *MockProblemService_Expecter) CreateProblemLabel(ctx interface{}, kind interface{}, slug interface{}, name interface{}) *MockProblemService_CreateProblemLabel_Call {
	return &MockProblemService_CreateProblemLabel_Call{Call: _e.mock.On("CreateProblemLabel", ctx, kind, slug, name)}
}

func (_c *MockProblemService_CreateProblemLabel_Call) Run(run func(ctx context.Context, kind string, slug string, name string)) *MockProblemService_CreateProblemLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProblemService_CreateProblemLabel_Call) Return(problemLabel *domain.ProblemLabel, err error) *MockProblemService_CreateProblemLabel_Call {
	_c.Call.Return(problemLabel, err)
	return _c
}

func (_c *MockProblemService_CreateProblemLabel_Call) RunAndReturn(run func(ctx context.Context, kind string, slug string, name string) (*domain.ProblemLabel, error)) *MockProblemService_CreateProblemLabel_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProblemLabel provides a mock function for the type MockProblemService
func (_mock *MockProblemService) DeleteProblemLabel(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProblemLabel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProblemService_DeleteProblemLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProblemLabel'
type MockProblemService_DeleteProblemLabel_Call struct {
	*mock.Call
}

// DeleteProblemLabel is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProblemService_Expecter) DeleteProblemLabel(ctx interface{}, id interface{}) *MockProblemService_DeleteProblemLabel_Call {
	return &MockProblemService_DeleteProblemLabel_Call{Call: _e.mock.On("DeleteProblemLabel", ctx, id)}
}

func (_c *MockProblemService_DeleteProblemLabel_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProblemService_DeleteProblemLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProblemService_DeleteProblemLabel_Call) Return(err error) *MockProblemService_DeleteProblemLabel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProblemService_DeleteProblemLabel_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockProblemService_DeleteProblemLabel_Call {
	_c.Call.Return(run)
	return _c
}

// GetProblem provides a mock function for the type MockProblemService
func (_mock *MockProblemService) GetProblem(ctx context.Context, rawID string) (*domain.Problem, error) {
	ret := _mock.Called(ctx, rawID)

	if len(ret) == 0 {
		panic("no return value specified for GetProblem")
	}

	var r0 *domain.Problem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Problem, error)); ok {
		return returnFunc(ctx, rawID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Problem); ok {
		r0 = returnFunc(ctx, rawID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Problem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, rawID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProblemService_GetProblem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProblem'
type MockProblemService_GetProblem_Call struct {
	*mock.Call
}

// GetProblem is a helper method to define mock.On call
//   - ctx context.Context
//   - rawID string
func (_e *MockProblemService_Expecter) GetProblem(ctx interface{}, rawID interface{}) *MockProblemService_GetProblem_Call {
	return &MockProblemService_GetProblem_Call{Call: _e.mock.On("GetProblem", ctx, rawID)}
}

func (_c *MockProblemService_GetProblem_Call) Run(run func(ctx context.Context, rawID string)) *MockProblemService_GetProblem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProblemService_GetProblem_Call) Return(problem *domain.Problem, err error) *MockProblemService_GetProblem_Call {
	_c.Call.Return(problem, err)
	return _c
}

func (_c *MockProblemService_GetProblem_Call) RunAndReturn(run func(ctx context.Context, rawID string) (*domain.Problem, error)) *MockProblemService_GetProblem_Call {
	_c.Call.Return(run)
	return _c
}

// GetProblemTestCases provides a mock function for the type MockProblemService
func (_mock *MockProblemService) GetProblemTestCases(ctx context.Context, id uuid.UUID) ([]domain.TestCase, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProblemTestCases")
	}

	var r0 []domain.TestCase
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.TestCase, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.TestCase); ok {
		r0 = returnFunc(ctx, id)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]domain.TestCase)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockProblemService_GetProblemTestCases_Call struct {
	*mock.Call
}

func (_e *MockProblemService_Expecter) GetProblemTestCases(ctx interface{}, id interface{}) *MockProblemService_GetProblemTestCases_Call {
	return &MockProblemService_GetProblemTestCases_Call{Call: _e.mock.On("GetProblemTestCases", ctx, id)}
}

func (_c *MockProblemService_GetProblemTestCases_Call) Return(testCases []domain.TestCase, err error) *MockProblemService_GetProblemTestCases_Call {
	_c.Call.Return(testCases, err)
	return _c
}

// UpdateProblem provides a mock function for the type MockProblemService
func (_mock *MockProblemService) UpdateProblem(ctx context.Context, id uuid.UUID, manifest domain.ProblemManifest) (*domain.Problem, error) {
	ret := _mock.Called(ctx, id, manifest)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProblem")
	}

	var r0 *domain.Problem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.ProblemManifest) (*domain.Problem, error)); ok {
		return returnFunc(ctx, id, manifest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.ProblemManifest) *domain.Problem); ok {
		r0 = returnFunc(ctx, id, manifest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Problem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.ProblemManifest) error); ok {
		r1 = returnFunc(ctx, id, manifest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProblemService_UpdateProblem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProblem'
type MockProblemService_UpdateProblem_Call struct {
	*mock.Call
}

// UpdateProblem is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - manifest domain.ProblemManifest
func (_e *MockProblemService_Expecter) UpdateProblem(ctx interface{}, id interface{}, manifest interface{}) *MockProblemService_UpdateProblem_Call {
	return &MockProblemService_UpdateProblem_Call{Call: _e.mock.On("UpdateProblem", ctx, id, manifest)}
}

func (_c *MockProblemService_UpdateProblem_Call) Run(run func(ctx context.Context, id uuid.UUID, manifest domain.ProblemManifest)) *MockProblemService_UpdateProblem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.ProblemManifest
		if args[2] != nil {
			arg2 = args[2].(domain.ProblemManifest)
		}
		run(arg0, arg1, arg2)
	})
	return _c
}

func (_c *MockProblemService_UpdateProblem_Call) Return(problem *domain.Problem, err error) *MockProblemService_UpdateProblem_Call {
	_c.Call.Return(problem, err)
	return _c
}

func (_c *MockProblemService_UpdateProblem_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, manifest domain.ProblemManifest) (*domain.Problem, error)) *MockProblemService_UpdateProblem_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProblemWithTestCases provides a mock function for the type MockProblemService
func (_mock *MockProblemService) UpdateProblemWithTestCases(ctx context.Context, id uuid.UUID, manifest domain.ProblemManifest, testCases []domain.TestCase) (*domain.Problem, error) {
	ret := _mock.Called(ctx, id, manifest, testCases)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProblemWithTestCases")
	}

	var r0 *domain.Problem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.ProblemManifest, []domain.TestCase) (*domain.Problem, error)); ok {
		return returnFunc(ctx, id, manifest, testCases)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.ProblemManifest, []domain.TestCase) *domain.Problem); ok {
		r0 = returnFunc(ctx, id, manifest, testCases)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*domain.Problem)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.ProblemManifest, []domain.TestCase) error); ok {
		r1 = returnFunc(ctx, id, manifest, testCases)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockProblemService_UpdateProblemWithTestCases_Call struct {
	*mock.Call
}

func (_e *MockProblemService_Expecter) UpdateProblemWithTestCases(ctx interface{}, id interface{}, manifest interface{}, testCases interface{}) *MockProblemService_UpdateProblemWithTestCases_Call {
	return &MockProblemService_UpdateProblemWithTestCases_Call{Call: _e.mock.On("UpdateProblemWithTestCases", ctx, id, manifest, testCases)}
}

func (_c *MockProblemService_UpdateProblemWithTestCases_Call) Return(problem *domain.Problem, err error) *MockProblemService_UpdateProblemWithTestCases_Call {
	_c.Call.Return(problem, err)
	return _c
}

// ListProblemLabelRecords provides a mock function for the type MockProblemService
func (_mock *MockProblemService) ListProblemLabelRecords(ctx context.Context, kind string) ([]domain.ProblemLabel, error) {
	ret := _mock.Called(ctx, kind)

	if len(ret) == 0 {
		panic("no return value specified for ListProblemLabelRecords")
	}

	var r0 []domain.ProblemLabel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.ProblemLabel, error)); ok {
		return returnFunc(ctx, kind)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.ProblemLabel); ok {
		r0 = returnFunc(ctx, kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProblemLabel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, kind)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProblemService_ListProblemLabelRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProblemLabelRecords'
type MockProblemService_ListProblemLabelRecords_Call struct {
	*mock.Call
}

// ListProblemLabelRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - kind string
func (_e *MockProblemService_Expecter) ListProblemLabelRecords(ctx interface{}, kind interface{}) *MockProblemService_ListProblemLabelRecords_Call {
	return &MockProblemService_ListProblemLabelRecords_Call{Call: _e.mock.On("ListProblemLabelRecords", ctx, kind)}
}

func (_c *MockProblemService_ListProblemLabelRecords_Call) Run(run func(ctx context.Context, kind string)) *MockProblemService_ListProblemLabelRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProblemService_ListProblemLabelRecords_Call) Return(problemLabels []domain.ProblemLabel, err error) *MockProblemService_ListProblemLabelRecords_Call {
	_c.Call.Return(problemLabels, err)
	return _c
}

func (_c *MockProblemService_ListProblemLabelRecords_Call) RunAndReturn(run func(ctx context.Context, kind string) ([]domain.ProblemLabel, error)) *MockProblemService_ListProblemLabelRecords_Call {
	_c.Call.Return(run)
	return _c
}

// ListProblemLabels provides a mock function for the type MockProblemService
func (_mock *MockProblemService) ListProblemLabels(ctx context.Context) ([]string, []string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListProblemLabels")
	}

	var r0 []string
	var r1 []string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, []string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) []string); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProblemService_ListProblemLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProblemLabels'
type MockProblemService_ListProblemLabels_Call struct {
	*mock.Call
}

// ListProblemLabels is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProblemService_Expecter) ListProblemLabels(ctx interface{}) *MockProblemService_ListProblemLabels_Call {
	return &MockProblemService_ListProblemLabels_Call{Call: _e.mock.On("ListProblemLabels", ctx)}
}

func (_c *MockProblemService_ListProblemLabels_Call) Run(run func(ctx context.Context)) *MockProblemService_ListProblemLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProblemService_ListProblemLabels_Call) Return(strings []string, strings1 []string, err error) *MockProblemService_ListProblemLabels_Call {
	_c.Call.Return(strings, strings1, err)
	return _c
}

func (_c *MockProblemService_ListProblemLabels_Call) RunAndReturn(run func(ctx context.Context) ([]string, []string, error)) *MockProblemService_ListProblemLabels_Call {
	_c.Call.Return(run)
	return _c
}

// ListProblems provides a mock function for the type MockProblemService
func (_mock *MockProblemService) ListProblems(ctx context.Context, filter out.ProblemFilter) ([]domain.Problem, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListProblems")
	}

	var r0 []domain.Problem
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, out.ProblemFilter) ([]domain.Problem, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, out.ProblemFilter) []domain.Problem); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Problem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, out.ProblemFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, out.ProblemFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProblemService_ListProblems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProblems'
type MockProblemService_ListProblems_Call struct {
	*mock.Call
}

// ListProblems is a helper method to define mock.On call
//   - ctx context.Context
//   - filter out.ProblemFilter
func (_e *MockProblemService_Expecter) ListProblems(ctx interface{}, filter interface{}) *MockProblemService_ListProblems_Call {
	return &MockProblemService_ListProblems_Call{Call: _e.mock.On("ListProblems", ctx, filter)}
}

func (_c *MockProblemService_ListProblems_Call) Run(run func(ctx context.Context, filter out.ProblemFilter)) *MockProblemService_ListProblems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 out.ProblemFilter
		if args[1] != nil {
			arg1 = args[1].(out.ProblemFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProblemService_ListProblems_Call) Return(problems []domain.Problem, n int, err error) *MockProblemService_ListProblems_Call {
	_c.Call.Return(problems, n, err)
	return _c
}

func (_c *MockProblemService_ListProblems_Call) RunAndReturn(run func(ctx context.Context, filter out.ProblemFilter) ([]domain.Problem, int, error)) *MockProblemService_ListProblems_Call {
	_c.Call.Return(run)
	return _c
}

// SuggestProblem provides a mock function for the type MockProblemService
func (_mock *MockProblemService) SuggestProblem(ctx context.Context, userID uuid.UUID) (*domain.Problem, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SuggestProblem")
	}

	var r0 *domain.Problem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Problem, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Problem); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Problem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProblemService_SuggestProblem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuggestProblem'
type MockProblemService_SuggestProblem_Call struct {
	*mock.Call
}

// SuggestProblem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockProblemService_Expecter) SuggestProblem(ctx interface{}, userID interface{}) *MockProblemService_SuggestProblem_Call {
	return &MockProblemService_SuggestProblem_Call{Call: _e.mock.On("SuggestProblem", ctx, userID)}
}

func (_c *MockProblemService_SuggestProblem_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockProblemService_SuggestProblem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProblemService_SuggestProblem_Call) Return(problem *domain.Problem, err error) *MockProblemService_SuggestProblem_Call {
	_c.Call.Return(problem, err)
	return _c
}

func (_c *MockProblemService_SuggestProblem_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*domain.Problem, error)) *MockProblemService_SuggestProblem_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProblemLabel provides a mock function for the type MockProblemService
func (_mock *MockProblemService) UpdateProblemLabel(ctx context.Context, id uuid.UUID, slug string, name string) (*domain.ProblemLabel, error) {
	ret := _mock.Called(ctx, id, slug, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProblemLabel")
	}

	var r0 *domain.ProblemLabel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (*domain.ProblemLabel, error)); ok {
		return returnFunc(ctx, id, slug, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) *domain.ProblemLabel); ok {
		r0 = returnFunc(ctx, id, slug, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProblemLabel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = returnFunc(ctx, id, slug, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProblemService_UpdateProblemLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProblemLabel'
type MockProblemService_UpdateProblemLabel_Call struct {
	*mock.Call
}

// UpdateProblemLabel is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - slug string
//   - name string
func (_e *MockProblemService_Expecter) UpdateProblemLabel(ctx interface{}, id interface{}, slug interface{}, name interface{}) *MockProblemService_UpdateProblemLabel_Call {
	return &MockProblemService_UpdateProblemLabel_Call{Call: _e.mock.On("UpdateProblemLabel", ctx, id, slug, name)}
}

func (_c *MockProblemService_UpdateProblemLabel_Call) Run(run func(ctx context.Context, id uuid.UUID, slug string, name string)) *MockProblemService_UpdateProblemLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProblemService_UpdateProblemLabel_Call) Return(problemLabel *domain.ProblemLabel, err error) *MockProblemService_UpdateProblemLabel_Call {
	_c.Call.Return(problemLabel, err)
	return _c
}

func (_c *MockProblemService_UpdateProblemLabel_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, slug string, name string) (*domain.ProblemLabel, error)) *MockProblemService_UpdateProblemLabel_Call {
	_c.Call.Return(run)
	return _c
}
