// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/judge-loop/internal/domain"
)

// NewMockTimerService creates a new instance of MockTimerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTimerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTimerService {
	mock := &MockTimerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTimerService is an autogenerated mock type for the TimerService type
type MockTimerService struct {
	mock.Mock
}

type MockTimerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTimerService) EXPECT() *MockTimerService_Expecter {
	return &MockTimerService_Expecter{mock: &_m.Mock}
}

// CurrentTimer provides a mock function for the type MockTimerService
func (_mock *MockTimerService) CurrentTimer(ctx context.Context, userID uuid.UUID) (*domain.TimerSession, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CurrentTimer")
	}

	var r0 *domain.TimerSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.TimerSession, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.TimerSession); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TimerSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTimerService_CurrentTimer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentTimer'
type MockTimerService_CurrentTimer_Call struct {
	*mock.Call
}

// CurrentTimer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTimerService_Expecter) CurrentTimer(ctx interface{}, userID interface{}) *MockTimerService_CurrentTimer_Call {
	return &MockTimerService_CurrentTimer_Call{Call: _e.mock.On("CurrentTimer", ctx, userID)}
}

func (_c *MockTimerService_CurrentTimer_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTimerService_CurrentTimer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTimerService_CurrentTimer_Call) Return(timerSession *domain.TimerSession, err error) *MockTimerService_CurrentTimer_Call {
	_c.Call.Return(timerSession, err)
	return _c
}

func (_c *MockTimerService_CurrentTimer_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*domain.TimerSession, error)) *MockTimerService_CurrentTimer_Call {
	_c.Call.Return(run)
	return _c
}

// StartTimer provides a mock function for the type MockTimerService
func (_mock *MockTimerService) StartTimer(ctx context.Context, userID uuid.UUID, problemID *uuid.UUID) (*domain.TimerSession, error) {
	ret := _mock.Called(ctx, userID, problemID)

	if len(ret) == 0 {
		panic("no return value specified for StartTimer")
	}

	var r0 *domain.TimerSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) (*domain.TimerSession, error)); ok {
		return returnFunc(ctx, userID, problemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) *domain.TimerSession); ok {
		r0 = returnFunc(ctx, userID, problemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TimerSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, problemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTimerService_StartTimer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartTimer'
type MockTimerService_StartTimer_Call struct {
	*mock.Call
}

// StartTimer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - problemID *uuid.UUID
func (_e *MockTimerService_Expecter) StartTimer(ctx interface{}, userID interface{}, problemID interface{}) *MockTimerService_StartTimer_Call {
	return &MockTimerService_StartTimer_Call{Call: _e.mock.On("StartTimer", ctx, userID, problemID)}
}

func (_c *MockTimerService_StartTimer_Call) Run(run func(ctx context.Context, userID uuid.UUID, problemID *uuid.UUID)) *MockTimerService_StartTimer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTimerService_StartTimer_Call) Return(timerSession *domain.TimerSession, err error) *MockTimerService_StartTimer_Call {
	_c.Call.Return(timerSession, err)
	return _c
}

func (_c *MockTimerService_StartTimer_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, problemID *uuid.UUID) (*domain.TimerSession, error)) *MockTimerService_StartTimer_Call {
	_c.Call.Return(run)
	return _c
}

// StopTimer provides a mock function for the type MockTimerService
func (_mock *MockTimerService) StopTimer(ctx context.Context, userID uuid.UUID) (*domain.TimerSession, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for StopTimer")
	}

	var r0 *domain.TimerSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.TimerSession, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.TimerSession); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TimerSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTimerService_StopTimer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopTimer'
type MockTimerService_StopTimer_Call struct {
	*mock.Call
}

// StopTimer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTimerService_Expecter) StopTimer(ctx interface{}, userID interface{}) *MockTimerService_StopTimer_Call {
	return &MockTimerService_StopTimer_Call{Call: _e.mock.On("StopTimer", ctx, userID)}
}

func (_c *MockTimerService_StopTimer_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTimerService_StopTimer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTimerService_StopTimer_Call) Return(timerSession *domain.TimerSession, err error) *MockTimerService_StopTimer_Call {
	_c.Call.Return(timerSession, err)
	return _c
}

func (_c *MockTimerService_StopTimer_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*domain.TimerSession, error)) *MockTimerService_StopTimer_Call {
	_c.Call.Return(run)
	return _c
}
