// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/judge-loop/internal/domain"
)

// NewMockSubmissionService creates a new instance of MockSubmissionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubmissionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubmissionService {
	mock := &MockSubmissionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubmissionService is an autogenerated mock type for the SubmissionService type
type MockSubmissionService struct {
	mock.Mock
}

type MockSubmissionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubmissionService) EXPECT() *MockSubmissionService_Expecter {
	return &MockSubmissionService_Expecter{mock: &_m.Mock}
}

// CreateSubmission provides a mock function for the type MockSubmissionService
func (_mock *MockSubmissionService) CreateSubmission(ctx context.Context, userID uuid.UUID, problemID uuid.UUID, language string, code string, sessionID *uuid.UUID) (*domain.Submission, error) {
	ret := _mock.Called(ctx, userID, problemID, language, code, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubmission")
	}

	var r0 *domain.Submission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, *uuid.UUID) (*domain.Submission, error)); ok {
		return returnFunc(ctx, userID, problemID, language, code, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, *uuid.UUID) *domain.Submission); ok {
		r0 = returnFunc(ctx, userID, problemID, language, code, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Submission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, string, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, problemID, language, code, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionService_CreateSubmission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubmission'
type MockSubmissionService_CreateSubmission_Call struct {
	*mock.Call
}

// CreateSubmission is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - problemID uuid.UUID
//   - language string
//   - code string
//   - sessionID *uuid.UUID
func (_e *MockSubmissionService_Expecter) CreateSubmission(ctx interface{}, userID interface{}, problemID interface{}, language interface{}, code interface{}, sessionID interface{}) *MockSubmissionService_CreateSubmission_Call {
	return &MockSubmissionService_CreateSubmission_Call{Call: _e.mock.On("CreateSubmission", ctx, userID, problemID, language, code, sessionID)}
}

func (_c *MockSubmissionService_CreateSubmission_Call) Run(run func(ctx context.Context, userID uuid.UUID, problemID uuid.UUID, language string, code string, sessionID *uuid.UUID)) *MockSubmissionService_CreateSubmission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 *uuid.UUID
		if args[5] != nil {
			arg5 = args[5].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockSubmissionService_CreateSubmission_Call) Return(submission *domain.Submission, err error) *MockSubmissionService_CreateSubmission_Call {
	_c.Call.Return(submission, err)
	return _c
}

func (_c *MockSubmissionService_CreateSubmission_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, problemID uuid.UUID, language string, code string, sessionID *uuid.UUID) (*domain.Submission, error)) *MockSubmissionService_CreateSubmission_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubmission provides a mock function for the type MockSubmissionService
func (_mock *MockSubmissionService) GetSubmission(ctx context.Context, id uuid.UUID) (*domain.Submission, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSubmission")
	}

	var r0 *domain.Submission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Submission, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Submission); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Submission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionService_GetSubmission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubmission'
type MockSubmissionService_GetSubmission_Call struct {
	*mock.Call
}

// GetSubmission is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSubmissionService_Expecter) GetSubmission(ctx interface{}, id interface{}) *MockSubmissionService_GetSubmission_Call {
	return &MockSubmissionService_GetSubmission_Call{Call: _e.mock.On("GetSubmission", ctx, id)}
}

func (_c *MockSubmissionService_GetSubmission_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSubmissionService_GetSubmission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmissionService_GetSubmission_Call) Return(submission *domain.Submission, err error) *MockSubmissionService_GetSubmission_Call {
	_c.Call.Return(submission, err)
	return _c
}

func (_c *MockSubmissionService_GetSubmission_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Submission, error)) *MockSubmissionService_GetSubmission_Call {
	_c.Call.Return(run)
	return _c
}

// ListSubmissions provides a mock function for the type MockSubmissionService
func (_mock *MockSubmissionService) ListSubmissions(ctx context.Context, userID uuid.UUID, problemID *uuid.UUID, limit int, offset int) ([]domain.Submission, error) {
	ret := _mock.Called(ctx, userID, problemID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListSubmissions")
	}

	var r0 []domain.Submission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, int, int) ([]domain.Submission, error)); ok {
		return returnFunc(ctx, userID, problemID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, int, int) []domain.Submission); ok {
		r0 = returnFunc(ctx, userID, problemID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Submission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *uuid.UUID, int, int) error); ok {
		r1 = returnFunc(ctx, userID, problemID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubmissionService_ListSubmissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSubmissions'
type MockSubmissionService_ListSubmissions_Call struct {
	*mock.Call
}

// ListSubmissions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - problemID *uuid.UUID
//   - limit int
//   - offset int
func (_e *MockSubmissionService_Expecter) ListSubmissions(ctx interface{}, userID interface{}, problemID interface{}, limit interface{}, offset interface{}) *MockSubmissionService_ListSubmissions_Call {
	return &MockSubmissionService_ListSubmissions_Call{Call: _e.mock.On("ListSubmissions", ctx, userID, problemID, limit, offset)}
}

func (_c *MockSubmissionService_ListSubmissions_Call) Run(run func(ctx context.Context, userID uuid.UUID, problemID *uuid.UUID, limit int, offset int)) *MockSubmissionService_ListSubmissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockSubmissionService_ListSubmissions_Call) Return(submissions []domain.Submission, err error) *MockSubmissionService_ListSubmissions_Call {
	_c.Call.Return(submissions, err)
	return _c
}

func (_c *MockSubmissionService_ListSubmissions_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, problemID *uuid.UUID, limit int, offset int) ([]domain.Submission, error)) *MockSubmissionService_ListSubmissions_Call {
	_c.Call.Return(run)
	return _c
}
