// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/judge-loop/internal/domain"
	"github.com/tuannm99/judge-loop/internal/port/out"
)

// NewMockProblemService creates a new instance of MockProblemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProblemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProblemService {
	mock := &MockProblemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProblemService is an autogenerated mock type for the ProblemService type
type MockProblemService struct {
	mock.Mock
}

type MockProblemService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProblemService) EXPECT() *MockProblemService_Expecter {
	return &MockProblemService_Expecter{mock: &_m.Mock}
}

// GetProblem provides a mock function for the type MockProblemService
func (_mock *MockProblemService) GetProblem(ctx context.Context, rawID string) (*domain.Problem, error) {
	ret := _mock.Called(ctx, rawID)

	if len(ret) == 0 {
		panic("no return value specified for GetProblem")
	}

	var r0 *domain.Problem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Problem, error)); ok {
		return returnFunc(ctx, rawID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Problem); ok {
		r0 = returnFunc(ctx, rawID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Problem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, rawID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProblemService_GetProblem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProblem'
type MockProblemService_GetProblem_Call struct {
	*mock.Call
}

// GetProblem is a helper method to define mock.On call
//   - ctx context.Context
//   - rawID string
func (_e *MockProblemService_Expecter) GetProblem(ctx interface{}, rawID interface{}) *MockProblemService_GetProblem_Call {
	return &MockProblemService_GetProblem_Call{Call: _e.mock.On("GetProblem", ctx, rawID)}
}

func (_c *MockProblemService_GetProblem_Call) Run(run func(ctx context.Context, rawID string)) *MockProblemService_GetProblem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProblemService_GetProblem_Call) Return(problem *domain.Problem, err error) *MockProblemService_GetProblem_Call {
	_c.Call.Return(problem, err)
	return _c
}

func (_c *MockProblemService_GetProblem_Call) RunAndReturn(run func(ctx context.Context, rawID string) (*domain.Problem, error)) *MockProblemService_GetProblem_Call {
	_c.Call.Return(run)
	return _c
}

// ListProblems provides a mock function for the type MockProblemService
func (_mock *MockProblemService) ListProblems(ctx context.Context, filter out.ProblemFilter) ([]domain.Problem, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListProblems")
	}

	var r0 []domain.Problem
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, out.ProblemFilter) ([]domain.Problem, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, out.ProblemFilter) []domain.Problem); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Problem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, out.ProblemFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, out.ProblemFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProblemService_ListProblems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProblems'
type MockProblemService_ListProblems_Call struct {
	*mock.Call
}

// ListProblems is a helper method to define mock.On call
//   - ctx context.Context
//   - filter out.ProblemFilter
func (_e *MockProblemService_Expecter) ListProblems(ctx interface{}, filter interface{}) *MockProblemService_ListProblems_Call {
	return &MockProblemService_ListProblems_Call{Call: _e.mock.On("ListProblems", ctx, filter)}
}

func (_c *MockProblemService_ListProblems_Call) Run(run func(ctx context.Context, filter out.ProblemFilter)) *MockProblemService_ListProblems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 out.ProblemFilter
		if args[1] != nil {
			arg1 = args[1].(out.ProblemFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProblemService_ListProblems_Call) Return(problems []domain.Problem, n int, err error) *MockProblemService_ListProblems_Call {
	_c.Call.Return(problems, n, err)
	return _c
}

func (_c *MockProblemService_ListProblems_Call) RunAndReturn(run func(ctx context.Context, filter out.ProblemFilter) ([]domain.Problem, int, error)) *MockProblemService_ListProblems_Call {
	_c.Call.Return(run)
	return _c
}

// SuggestProblem provides a mock function for the type MockProblemService
func (_mock *MockProblemService) SuggestProblem(ctx context.Context, userID uuid.UUID) (*domain.Problem, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SuggestProblem")
	}

	var r0 *domain.Problem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Problem, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Problem); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Problem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProblemService_SuggestProblem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuggestProblem'
type MockProblemService_SuggestProblem_Call struct {
	*mock.Call
}

// SuggestProblem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockProblemService_Expecter) SuggestProblem(ctx interface{}, userID interface{}) *MockProblemService_SuggestProblem_Call {
	return &MockProblemService_SuggestProblem_Call{Call: _e.mock.On("SuggestProblem", ctx, userID)}
}

func (_c *MockProblemService_SuggestProblem_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockProblemService_SuggestProblem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProblemService_SuggestProblem_Call) Return(problem *domain.Problem, err error) *MockProblemService_SuggestProblem_Call {
	_c.Call.Return(problem, err)
	return _c
}

func (_c *MockProblemService_SuggestProblem_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*domain.Problem, error)) *MockProblemService_SuggestProblem_Call {
	_c.Call.Return(run)
	return _c
}
