// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/judge-loop/internal/domain"
)

// NewMockMissionService creates a new instance of MockMissionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMissionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMissionService {
	mock := &MockMissionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMissionService is an autogenerated mock type for the MissionService type
type MockMissionService struct {
	mock.Mock
}

type MockMissionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMissionService) EXPECT() *MockMissionService_Expecter {
	return &MockMissionService_Expecter{mock: &_m.Mock}
}

// GetDailyMission provides a mock function for the type MockMissionService
func (_mock *MockMissionService) GetDailyMission(ctx context.Context, userID uuid.UUID) (*domain.DailyMission, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyMission")
	}

	var r0 *domain.DailyMission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.DailyMission, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.DailyMission); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DailyMission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMissionService_GetDailyMission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDailyMission'
type MockMissionService_GetDailyMission_Call struct {
	*mock.Call
}

// GetDailyMission is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockMissionService_Expecter) GetDailyMission(ctx interface{}, userID interface{}) *MockMissionService_GetDailyMission_Call {
	return &MockMissionService_GetDailyMission_Call{Call: _e.mock.On("GetDailyMission", ctx, userID)}
}

func (_c *MockMissionService_GetDailyMission_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockMissionService_GetDailyMission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMissionService_GetDailyMission_Call) Return(dailyMission *domain.DailyMission, err error) *MockMissionService_GetDailyMission_Call {
	_c.Call.Return(dailyMission, err)
	return _c
}

func (_c *MockMissionService_GetDailyMission_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*domain.DailyMission, error)) *MockMissionService_GetDailyMission_Call {
	_c.Call.Return(run)
	return _c
}
