// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/judge-loop/internal/domain"
	"github.com/tuannm99/judge-loop/internal/port/out"
)

// NewMockRegistryService creates a new instance of MockRegistryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistryService {
	mock := &MockRegistryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistryService is an autogenerated mock type for the RegistryService type
type MockRegistryService struct {
	mock.Mock
}

type MockRegistryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistryService) EXPECT() *MockRegistryService_Expecter {
	return &MockRegistryService_Expecter{mock: &_m.Mock}
}

// GetRegistryVersion provides a mock function for the type MockRegistryService
func (_mock *MockRegistryService) GetRegistryVersion(ctx context.Context) (*out.RegistryVersion, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRegistryVersion")
	}

	var r0 *out.RegistryVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*out.RegistryVersion, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *out.RegistryVersion); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*out.RegistryVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistryService_GetRegistryVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegistryVersion'
type MockRegistryService_GetRegistryVersion_Call struct {
	*mock.Call
}

// GetRegistryVersion is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRegistryService_Expecter) GetRegistryVersion(ctx interface{}) *MockRegistryService_GetRegistryVersion_Call {
	return &MockRegistryService_GetRegistryVersion_Call{Call: _e.mock.On("GetRegistryVersion", ctx)}
}

func (_c *MockRegistryService_GetRegistryVersion_Call) Run(run func(ctx context.Context)) *MockRegistryService_GetRegistryVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistryService_GetRegistryVersion_Call) Return(registryVersion *out.RegistryVersion, err error) *MockRegistryService_GetRegistryVersion_Call {
	_c.Call.Return(registryVersion, err)
	return _c
}

func (_c *MockRegistryService_GetRegistryVersion_Call) RunAndReturn(run func(ctx context.Context) (*out.RegistryVersion, error)) *MockRegistryService_GetRegistryVersion_Call {
	_c.Call.Return(run)
	return _c
}

// SyncRegistry provides a mock function for the type MockRegistryService
func (_mock *MockRegistryService) SyncRegistry(ctx context.Context, version string, updatedAt time.Time, problems []domain.ProblemManifest, manifests []domain.ManifestRef) (int, error) {
	ret := _mock.Called(ctx, version, updatedAt, problems, manifests)

	if len(ret) == 0 {
		panic("no return value specified for SyncRegistry")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, []domain.ProblemManifest, []domain.ManifestRef) (int, error)); ok {
		return returnFunc(ctx, version, updatedAt, problems, manifests)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, []domain.ProblemManifest, []domain.ManifestRef) int); ok {
		r0 = returnFunc(ctx, version, updatedAt, problems, manifests)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, []domain.ProblemManifest, []domain.ManifestRef) error); ok {
		r1 = returnFunc(ctx, version, updatedAt, problems, manifests)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistryService_SyncRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncRegistry'
type MockRegistryService_SyncRegistry_Call struct {
	*mock.Call
}

// SyncRegistry is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
//   - updatedAt time.Time
//   - problems []domain.ProblemManifest
//   - manifests []domain.ManifestRef
func (_e *MockRegistryService_Expecter) SyncRegistry(ctx interface{}, version interface{}, updatedAt interface{}, problems interface{}, manifests interface{}) *MockRegistryService_SyncRegistry_Call {
	return &MockRegistryService_SyncRegistry_Call{Call: _e.mock.On("SyncRegistry", ctx, version, updatedAt, problems, manifests)}
}

func (_c *MockRegistryService_SyncRegistry_Call) Run(run func(ctx context.Context, version string, updatedAt time.Time, problems []domain.ProblemManifest, manifests []domain.ManifestRef)) *MockRegistryService_SyncRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 []domain.ProblemManifest
		if args[3] != nil {
			arg3 = args[3].([]domain.ProblemManifest)
		}
		var arg4 []domain.ManifestRef
		if args[4] != nil {
			arg4 = args[4].([]domain.ManifestRef)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRegistryService_SyncRegistry_Call) Return(n int, err error) *MockRegistryService_SyncRegistry_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRegistryService_SyncRegistry_Call) RunAndReturn(run func(ctx context.Context, version string, updatedAt time.Time, problems []domain.ProblemManifest, manifests []domain.ManifestRef) (int, error)) *MockRegistryService_SyncRegistry_Call {
	_c.Call.Return(run)
	return _c
}
