// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/judge-loop/internal/port/out"
)

// NewMockReviewService creates a new instance of MockReviewService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewService {
	mock := &MockReviewService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReviewService is an autogenerated mock type for the ReviewService type
type MockReviewService struct {
	mock.Mock
}

type MockReviewService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewService) EXPECT() *MockReviewService_Expecter {
	return &MockReviewService_Expecter{mock: &_m.Mock}
}

// GetReviewsToday provides a mock function for the type MockReviewService
func (_mock *MockReviewService) GetReviewsToday(ctx context.Context, userID uuid.UUID) ([]out.DueReview, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewsToday")
	}

	var r0 []out.DueReview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]out.DueReview, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []out.DueReview); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]out.DueReview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewService_GetReviewsToday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewsToday'
type MockReviewService_GetReviewsToday_Call struct {
	*mock.Call
}

// GetReviewsToday is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockReviewService_Expecter) GetReviewsToday(ctx interface{}, userID interface{}) *MockReviewService_GetReviewsToday_Call {
	return &MockReviewService_GetReviewsToday_Call{Call: _e.mock.On("GetReviewsToday", ctx, userID)}
}

func (_c *MockReviewService_GetReviewsToday_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockReviewService_GetReviewsToday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewService_GetReviewsToday_Call) Return(dueReviews []out.DueReview, err error) *MockReviewService_GetReviewsToday_Call {
	_c.Call.Return(dueReviews, err)
	return _c
}

func (_c *MockReviewService_GetReviewsToday_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]out.DueReview, error)) *MockReviewService_GetReviewsToday_Call {
	_c.Call.Return(run)
	return _c
}
