// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEvaluationService creates a new instance of MockEvaluationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvaluationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvaluationService {
	mock := &MockEvaluationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEvaluationService is an autogenerated mock type for the EvaluationService type
type MockEvaluationService struct {
	mock.Mock
}

type MockEvaluationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvaluationService) EXPECT() *MockEvaluationService_Expecter {
	return &MockEvaluationService_Expecter{mock: &_m.Mock}
}

// EvaluateSubmission provides a mock function for the type MockEvaluationService
func (_mock *MockEvaluationService) EvaluateSubmission(ctx context.Context, submissionID uuid.UUID, userID uuid.UUID, timeLimitSecs int) error {
	ret := _mock.Called(ctx, submissionID, userID, timeLimitSecs)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateSubmission")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) error); ok {
		r0 = returnFunc(ctx, submissionID, userID, timeLimitSecs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEvaluationService_EvaluateSubmission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluateSubmission'
type MockEvaluationService_EvaluateSubmission_Call struct {
	*mock.Call
}

// EvaluateSubmission is a helper method to define mock.On call
//   - ctx context.Context
//   - submissionID uuid.UUID
//   - userID uuid.UUID
//   - timeLimitSecs int
func (_e *MockEvaluationService_Expecter) EvaluateSubmission(ctx interface{}, submissionID interface{}, userID interface{}, timeLimitSecs interface{}) *MockEvaluationService_EvaluateSubmission_Call {
	return &MockEvaluationService_EvaluateSubmission_Call{Call: _e.mock.On("EvaluateSubmission", ctx, submissionID, userID, timeLimitSecs)}
}

func (_c *MockEvaluationService_EvaluateSubmission_Call) Run(run func(ctx context.Context, submissionID uuid.UUID, userID uuid.UUID, timeLimitSecs int)) *MockEvaluationService_EvaluateSubmission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEvaluationService_EvaluateSubmission_Call) Return(err error) *MockEvaluationService_EvaluateSubmission_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEvaluationService_EvaluateSubmission_Call) RunAndReturn(run func(ctx context.Context, submissionID uuid.UUID, userID uuid.UUID, timeLimitSecs int) error) *MockEvaluationService_EvaluateSubmission_Call {
	_c.Call.Return(run)
	return _c
}
