// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/judge-loop/internal/port/in"
	"github.com/tuannm99/judge-loop/internal/port/out"
)

// NewMockProgressService creates a new instance of MockProgressService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProgressService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProgressService {
	mock := &MockProgressService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProgressService is an autogenerated mock type for the ProgressService type
type MockProgressService struct {
	mock.Mock
}

type MockProgressService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProgressService) EXPECT() *MockProgressService_Expecter {
	return &MockProgressService_Expecter{mock: &_m.Mock}
}

// GetGoalProgress provides a mock function for the type MockProgressService
func (_mock *MockProgressService) GetGoalProgress(ctx context.Context, userID uuid.UUID) (in.GoalProgress, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetGoalProgress")
	}

	var r0 in.GoalProgress
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (in.GoalProgress, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) in.GoalProgress); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(in.GoalProgress)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProgressService_GetGoalProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGoalProgress'
type MockProgressService_GetGoalProgress_Call struct {
	*mock.Call
}

// GetGoalProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockProgressService_Expecter) GetGoalProgress(ctx interface{}, userID interface{}) *MockProgressService_GetGoalProgress_Call {
	return &MockProgressService_GetGoalProgress_Call{Call: _e.mock.On("GetGoalProgress", ctx, userID)}
}

func (_c *MockProgressService_GetGoalProgress_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockProgressService_GetGoalProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProgressService_GetGoalProgress_Call) Return(goalProgress in.GoalProgress, err error) *MockProgressService_GetGoalProgress_Call {
	_c.Call.Return(goalProgress, err)
	return _c
}

func (_c *MockProgressService_GetGoalProgress_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (in.GoalProgress, error)) *MockProgressService_GetGoalProgress_Call {
	_c.Call.Return(run)
	return _c
}

// GetProgressToday provides a mock function for the type MockProgressService
func (_mock *MockProgressService) GetProgressToday(ctx context.Context, userID uuid.UUID) (in.ProgressToday, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProgressToday")
	}

	var r0 in.ProgressToday
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (in.ProgressToday, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) in.ProgressToday); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(in.ProgressToday)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProgressService_GetProgressToday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProgressToday'
type MockProgressService_GetProgressToday_Call struct {
	*mock.Call
}

// GetProgressToday is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockProgressService_Expecter) GetProgressToday(ctx interface{}, userID interface{}) *MockProgressService_GetProgressToday_Call {
	return &MockProgressService_GetProgressToday_Call{Call: _e.mock.On("GetProgressToday", ctx, userID)}
}

func (_c *MockProgressService_GetProgressToday_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockProgressService_GetProgressToday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProgressService_GetProgressToday_Call) Return(progressToday in.ProgressToday, err error) *MockProgressService_GetProgressToday_Call {
	_c.Call.Return(progressToday, err)
	return _c
}

func (_c *MockProgressService_GetProgressToday_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (in.ProgressToday, error)) *MockProgressService_GetProgressToday_Call {
	_c.Call.Return(run)
	return _c
}

// GetStreak provides a mock function for the type MockProgressService
func (_mock *MockProgressService) GetStreak(ctx context.Context, userID uuid.UUID) (out.StreakInfo, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetStreak")
	}

	var r0 out.StreakInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (out.StreakInfo, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) out.StreakInfo); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(out.StreakInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProgressService_GetStreak_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStreak'
type MockProgressService_GetStreak_Call struct {
	*mock.Call
}

// GetStreak is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockProgressService_Expecter) GetStreak(ctx interface{}, userID interface{}) *MockProgressService_GetStreak_Call {
	return &MockProgressService_GetStreak_Call{Call: _e.mock.On("GetStreak", ctx, userID)}
}

func (_c *MockProgressService_GetStreak_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockProgressService_GetStreak_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProgressService_GetStreak_Call) Return(streakInfo out.StreakInfo, err error) *MockProgressService_GetStreak_Call {
	_c.Call.Return(streakInfo, err)
	return _c
}

func (_c *MockProgressService_GetStreak_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (out.StreakInfo, error)) *MockProgressService_GetStreak_Call {
	_c.Call.Return(run)
	return _c
}
