// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/tuannm99/judge-loop/internal/domain"
	"github.com/tuannm99/judge-loop/internal/port/in"
	"github.com/tuannm99/judge-loop/internal/port/out"
)

// NewMockAPIService creates a new instance of MockAPIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIService {
	mock := &MockAPIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIService is an autogenerated mock type for the APIService type
type MockAPIService struct {
	mock.Mock
}

type MockAPIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIService) EXPECT() *MockAPIService_Expecter {
	return &MockAPIService_Expecter{mock: &_m.Mock}
}

// CreateSubmission provides a mock function for the type MockAPIService
func (_mock *MockAPIService) CreateSubmission(ctx context.Context, userID uuid.UUID, problemID uuid.UUID, language string, code string, sessionID *uuid.UUID) (*domain.Submission, error) {
	ret := _mock.Called(ctx, userID, problemID, language, code, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubmission")
	}

	var r0 *domain.Submission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, *uuid.UUID) (*domain.Submission, error)); ok {
		return returnFunc(ctx, userID, problemID, language, code, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, *uuid.UUID) *domain.Submission); ok {
		r0 = returnFunc(ctx, userID, problemID, language, code, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Submission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, string, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, problemID, language, code, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIService_CreateSubmission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubmission'
type MockAPIService_CreateSubmission_Call struct {
	*mock.Call
}

// CreateSubmission is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - problemID uuid.UUID
//   - language string
//   - code string
//   - sessionID *uuid.UUID
func (_e *MockAPIService_Expecter) CreateSubmission(ctx interface{}, userID interface{}, problemID interface{}, language interface{}, code interface{}, sessionID interface{}) *MockAPIService_CreateSubmission_Call {
	return &MockAPIService_CreateSubmission_Call{Call: _e.mock.On("CreateSubmission", ctx, userID, problemID, language, code, sessionID)}
}

func (_c *MockAPIService_CreateSubmission_Call) Run(run func(ctx context.Context, userID uuid.UUID, problemID uuid.UUID, language string, code string, sessionID *uuid.UUID)) *MockAPIService_CreateSubmission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 *uuid.UUID
		if args[5] != nil {
			arg5 = args[5].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAPIService_CreateSubmission_Call) Return(submission *domain.Submission, err error) *MockAPIService_CreateSubmission_Call {
	_c.Call.Return(submission, err)
	return _c
}

func (_c *MockAPIService_CreateSubmission_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, problemID uuid.UUID, language string, code string, sessionID *uuid.UUID) (*domain.Submission, error)) *MockAPIService_CreateSubmission_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentTimer provides a mock function for the type MockAPIService
func (_mock *MockAPIService) CurrentTimer(ctx context.Context, userID uuid.UUID) (*domain.TimerSession, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CurrentTimer")
	}

	var r0 *domain.TimerSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.TimerSession, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.TimerSession); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TimerSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIService_CurrentTimer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentTimer'
type MockAPIService_CurrentTimer_Call struct {
	*mock.Call
}

// CurrentTimer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAPIService_Expecter) CurrentTimer(ctx interface{}, userID interface{}) *MockAPIService_CurrentTimer_Call {
	return &MockAPIService_CurrentTimer_Call{Call: _e.mock.On("CurrentTimer", ctx, userID)}
}

func (_c *MockAPIService_CurrentTimer_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAPIService_CurrentTimer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIService_CurrentTimer_Call) Return(timerSession *domain.TimerSession, err error) *MockAPIService_CurrentTimer_Call {
	_c.Call.Return(timerSession, err)
	return _c
}

func (_c *MockAPIService_CurrentTimer_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*domain.TimerSession, error)) *MockAPIService_CurrentTimer_Call {
	_c.Call.Return(run)
	return _c
}

// GetProblem provides a mock function for the type MockAPIService
func (_mock *MockAPIService) GetProblem(ctx context.Context, rawID string) (*domain.Problem, error) {
	ret := _mock.Called(ctx, rawID)

	if len(ret) == 0 {
		panic("no return value specified for GetProblem")
	}

	var r0 *domain.Problem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Problem, error)); ok {
		return returnFunc(ctx, rawID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Problem); ok {
		r0 = returnFunc(ctx, rawID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Problem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, rawID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIService_GetProblem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProblem'
type MockAPIService_GetProblem_Call struct {
	*mock.Call
}

// GetProblem is a helper method to define mock.On call
//   - ctx context.Context
//   - rawID string
func (_e *MockAPIService_Expecter) GetProblem(ctx interface{}, rawID interface{}) *MockAPIService_GetProblem_Call {
	return &MockAPIService_GetProblem_Call{Call: _e.mock.On("GetProblem", ctx, rawID)}
}

func (_c *MockAPIService_GetProblem_Call) Run(run func(ctx context.Context, rawID string)) *MockAPIService_GetProblem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIService_GetProblem_Call) Return(problem *domain.Problem, err error) *MockAPIService_GetProblem_Call {
	_c.Call.Return(problem, err)
	return _c
}

func (_c *MockAPIService_GetProblem_Call) RunAndReturn(run func(ctx context.Context, rawID string) (*domain.Problem, error)) *MockAPIService_GetProblem_Call {
	_c.Call.Return(run)
	return _c
}

// GetProgressToday provides a mock function for the type MockAPIService
func (_mock *MockAPIService) GetProgressToday(ctx context.Context, userID uuid.UUID) (in.ProgressToday, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProgressToday")
	}

	var r0 in.ProgressToday
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (in.ProgressToday, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) in.ProgressToday); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(in.ProgressToday)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIService_GetProgressToday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProgressToday'
type MockAPIService_GetProgressToday_Call struct {
	*mock.Call
}

// GetProgressToday is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAPIService_Expecter) GetProgressToday(ctx interface{}, userID interface{}) *MockAPIService_GetProgressToday_Call {
	return &MockAPIService_GetProgressToday_Call{Call: _e.mock.On("GetProgressToday", ctx, userID)}
}

func (_c *MockAPIService_GetProgressToday_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAPIService_GetProgressToday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIService_GetProgressToday_Call) Return(progressToday in.ProgressToday, err error) *MockAPIService_GetProgressToday_Call {
	_c.Call.Return(progressToday, err)
	return _c
}

func (_c *MockAPIService_GetProgressToday_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (in.ProgressToday, error)) *MockAPIService_GetProgressToday_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegistryVersion provides a mock function for the type MockAPIService
func (_mock *MockAPIService) GetRegistryVersion(ctx context.Context) (*out.RegistryVersion, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRegistryVersion")
	}

	var r0 *out.RegistryVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*out.RegistryVersion, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *out.RegistryVersion); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*out.RegistryVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIService_GetRegistryVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegistryVersion'
type MockAPIService_GetRegistryVersion_Call struct {
	*mock.Call
}

// GetRegistryVersion is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAPIService_Expecter) GetRegistryVersion(ctx interface{}) *MockAPIService_GetRegistryVersion_Call {
	return &MockAPIService_GetRegistryVersion_Call{Call: _e.mock.On("GetRegistryVersion", ctx)}
}

func (_c *MockAPIService_GetRegistryVersion_Call) Run(run func(ctx context.Context)) *MockAPIService_GetRegistryVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAPIService_GetRegistryVersion_Call) Return(registryVersion *out.RegistryVersion, err error) *MockAPIService_GetRegistryVersion_Call {
	_c.Call.Return(registryVersion, err)
	return _c
}

func (_c *MockAPIService_GetRegistryVersion_Call) RunAndReturn(run func(ctx context.Context) (*out.RegistryVersion, error)) *MockAPIService_GetRegistryVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetReviewsToday provides a mock function for the type MockAPIService
func (_mock *MockAPIService) GetReviewsToday(ctx context.Context, userID uuid.UUID) ([]out.DueReview, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewsToday")
	}

	var r0 []out.DueReview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]out.DueReview, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []out.DueReview); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]out.DueReview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIService_GetReviewsToday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewsToday'
type MockAPIService_GetReviewsToday_Call struct {
	*mock.Call
}

// GetReviewsToday is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAPIService_Expecter) GetReviewsToday(ctx interface{}, userID interface{}) *MockAPIService_GetReviewsToday_Call {
	return &MockAPIService_GetReviewsToday_Call{Call: _e.mock.On("GetReviewsToday", ctx, userID)}
}

func (_c *MockAPIService_GetReviewsToday_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAPIService_GetReviewsToday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIService_GetReviewsToday_Call) Return(dueReviews []out.DueReview, err error) *MockAPIService_GetReviewsToday_Call {
	_c.Call.Return(dueReviews, err)
	return _c
}

func (_c *MockAPIService_GetReviewsToday_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]out.DueReview, error)) *MockAPIService_GetReviewsToday_Call {
	_c.Call.Return(run)
	return _c
}

// GetStreak provides a mock function for the type MockAPIService
func (_mock *MockAPIService) GetStreak(ctx context.Context, userID uuid.UUID) (out.StreakInfo, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetStreak")
	}

	var r0 out.StreakInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (out.StreakInfo, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) out.StreakInfo); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(out.StreakInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIService_GetStreak_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStreak'
type MockAPIService_GetStreak_Call struct {
	*mock.Call
}

// GetStreak is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAPIService_Expecter) GetStreak(ctx interface{}, userID interface{}) *MockAPIService_GetStreak_Call {
	return &MockAPIService_GetStreak_Call{Call: _e.mock.On("GetStreak", ctx, userID)}
}

func (_c *MockAPIService_GetStreak_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAPIService_GetStreak_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIService_GetStreak_Call) Return(streakInfo out.StreakInfo, err error) *MockAPIService_GetStreak_Call {
	_c.Call.Return(streakInfo, err)
	return _c
}

func (_c *MockAPIService_GetStreak_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (out.StreakInfo, error)) *MockAPIService_GetStreak_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubmission provides a mock function for the type MockAPIService
func (_mock *MockAPIService) GetSubmission(ctx context.Context, id uuid.UUID) (*domain.Submission, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSubmission")
	}

	var r0 *domain.Submission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Submission, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Submission); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Submission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIService_GetSubmission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubmission'
type MockAPIService_GetSubmission_Call struct {
	*mock.Call
}

// GetSubmission is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAPIService_Expecter) GetSubmission(ctx interface{}, id interface{}) *MockAPIService_GetSubmission_Call {
	return &MockAPIService_GetSubmission_Call{Call: _e.mock.On("GetSubmission", ctx, id)}
}

func (_c *MockAPIService_GetSubmission_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAPIService_GetSubmission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIService_GetSubmission_Call) Return(submission *domain.Submission, err error) *MockAPIService_GetSubmission_Call {
	_c.Call.Return(submission, err)
	return _c
}

func (_c *MockAPIService_GetSubmission_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Submission, error)) *MockAPIService_GetSubmission_Call {
	_c.Call.Return(run)
	return _c
}

// ListProblems provides a mock function for the type MockAPIService
func (_mock *MockAPIService) ListProblems(ctx context.Context, filter out.ProblemFilter) ([]domain.Problem, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListProblems")
	}

	var r0 []domain.Problem
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, out.ProblemFilter) ([]domain.Problem, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, out.ProblemFilter) []domain.Problem); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Problem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, out.ProblemFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, out.ProblemFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAPIService_ListProblems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProblems'
type MockAPIService_ListProblems_Call struct {
	*mock.Call
}

// ListProblems is a helper method to define mock.On call
//   - ctx context.Context
//   - filter out.ProblemFilter
func (_e *MockAPIService_Expecter) ListProblems(ctx interface{}, filter interface{}) *MockAPIService_ListProblems_Call {
	return &MockAPIService_ListProblems_Call{Call: _e.mock.On("ListProblems", ctx, filter)}
}

func (_c *MockAPIService_ListProblems_Call) Run(run func(ctx context.Context, filter out.ProblemFilter)) *MockAPIService_ListProblems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 out.ProblemFilter
		if args[1] != nil {
			arg1 = args[1].(out.ProblemFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIService_ListProblems_Call) Return(problems []domain.Problem, n int, err error) *MockAPIService_ListProblems_Call {
	_c.Call.Return(problems, n, err)
	return _c
}

func (_c *MockAPIService_ListProblems_Call) RunAndReturn(run func(ctx context.Context, filter out.ProblemFilter) ([]domain.Problem, int, error)) *MockAPIService_ListProblems_Call {
	_c.Call.Return(run)
	return _c
}

// ListSubmissions provides a mock function for the type MockAPIService
func (_mock *MockAPIService) ListSubmissions(ctx context.Context, userID uuid.UUID, problemID *uuid.UUID, limit int, offset int) ([]domain.Submission, error) {
	ret := _mock.Called(ctx, userID, problemID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListSubmissions")
	}

	var r0 []domain.Submission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, int, int) ([]domain.Submission, error)); ok {
		return returnFunc(ctx, userID, problemID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, int, int) []domain.Submission); ok {
		r0 = returnFunc(ctx, userID, problemID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Submission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *uuid.UUID, int, int) error); ok {
		r1 = returnFunc(ctx, userID, problemID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIService_ListSubmissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSubmissions'
type MockAPIService_ListSubmissions_Call struct {
	*mock.Call
}

// ListSubmissions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - problemID *uuid.UUID
//   - limit int
//   - offset int
func (_e *MockAPIService_Expecter) ListSubmissions(ctx interface{}, userID interface{}, problemID interface{}, limit interface{}, offset interface{}) *MockAPIService_ListSubmissions_Call {
	return &MockAPIService_ListSubmissions_Call{Call: _e.mock.On("ListSubmissions", ctx, userID, problemID, limit, offset)}
}

func (_c *MockAPIService_ListSubmissions_Call) Run(run func(ctx context.Context, userID uuid.UUID, problemID *uuid.UUID, limit int, offset int)) *MockAPIService_ListSubmissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAPIService_ListSubmissions_Call) Return(submissions []domain.Submission, err error) *MockAPIService_ListSubmissions_Call {
	_c.Call.Return(submissions, err)
	return _c
}

func (_c *MockAPIService_ListSubmissions_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, problemID *uuid.UUID, limit int, offset int) ([]domain.Submission, error)) *MockAPIService_ListSubmissions_Call {
	_c.Call.Return(run)
	return _c
}

// StartTimer provides a mock function for the type MockAPIService
func (_mock *MockAPIService) StartTimer(ctx context.Context, userID uuid.UUID, problemID *uuid.UUID) (*domain.TimerSession, error) {
	ret := _mock.Called(ctx, userID, problemID)

	if len(ret) == 0 {
		panic("no return value specified for StartTimer")
	}

	var r0 *domain.TimerSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) (*domain.TimerSession, error)); ok {
		return returnFunc(ctx, userID, problemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) *domain.TimerSession); ok {
		r0 = returnFunc(ctx, userID, problemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TimerSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, problemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIService_StartTimer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartTimer'
type MockAPIService_StartTimer_Call struct {
	*mock.Call
}

// StartTimer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - problemID *uuid.UUID
func (_e *MockAPIService_Expecter) StartTimer(ctx interface{}, userID interface{}, problemID interface{}) *MockAPIService_StartTimer_Call {
	return &MockAPIService_StartTimer_Call{Call: _e.mock.On("StartTimer", ctx, userID, problemID)}
}

func (_c *MockAPIService_StartTimer_Call) Run(run func(ctx context.Context, userID uuid.UUID, problemID *uuid.UUID)) *MockAPIService_StartTimer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPIService_StartTimer_Call) Return(timerSession *domain.TimerSession, err error) *MockAPIService_StartTimer_Call {
	_c.Call.Return(timerSession, err)
	return _c
}

func (_c *MockAPIService_StartTimer_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, problemID *uuid.UUID) (*domain.TimerSession, error)) *MockAPIService_StartTimer_Call {
	_c.Call.Return(run)
	return _c
}

// StopTimer provides a mock function for the type MockAPIService
func (_mock *MockAPIService) StopTimer(ctx context.Context, userID uuid.UUID) (*domain.TimerSession, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for StopTimer")
	}

	var r0 *domain.TimerSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.TimerSession, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.TimerSession); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TimerSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIService_StopTimer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopTimer'
type MockAPIService_StopTimer_Call struct {
	*mock.Call
}

// StopTimer is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAPIService_Expecter) StopTimer(ctx interface{}, userID interface{}) *MockAPIService_StopTimer_Call {
	return &MockAPIService_StopTimer_Call{Call: _e.mock.On("StopTimer", ctx, userID)}
}

func (_c *MockAPIService_StopTimer_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAPIService_StopTimer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIService_StopTimer_Call) Return(timerSession *domain.TimerSession, err error) *MockAPIService_StopTimer_Call {
	_c.Call.Return(timerSession, err)
	return _c
}

func (_c *MockAPIService_StopTimer_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*domain.TimerSession, error)) *MockAPIService_StopTimer_Call {
	_c.Call.Return(run)
	return _c
}

// SuggestProblem provides a mock function for the type MockAPIService
func (_mock *MockAPIService) SuggestProblem(ctx context.Context, userID uuid.UUID) (*domain.Problem, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SuggestProblem")
	}

	var r0 *domain.Problem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Problem, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Problem); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Problem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIService_SuggestProblem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuggestProblem'
type MockAPIService_SuggestProblem_Call struct {
	*mock.Call
}

// SuggestProblem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAPIService_Expecter) SuggestProblem(ctx interface{}, userID interface{}) *MockAPIService_SuggestProblem_Call {
	return &MockAPIService_SuggestProblem_Call{Call: _e.mock.On("SuggestProblem", ctx, userID)}
}

func (_c *MockAPIService_SuggestProblem_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAPIService_SuggestProblem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIService_SuggestProblem_Call) Return(problem *domain.Problem, err error) *MockAPIService_SuggestProblem_Call {
	_c.Call.Return(problem, err)
	return _c
}

func (_c *MockAPIService_SuggestProblem_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*domain.Problem, error)) *MockAPIService_SuggestProblem_Call {
	_c.Call.Return(run)
	return _c
}

// SyncRegistry provides a mock function for the type MockAPIService
func (_mock *MockAPIService) SyncRegistry(ctx context.Context, version string, updatedAt time.Time, problems []domain.ProblemManifest, manifests []domain.ManifestRef) (int, error) {
	ret := _mock.Called(ctx, version, updatedAt, problems, manifests)

	if len(ret) == 0 {
		panic("no return value specified for SyncRegistry")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, []domain.ProblemManifest, []domain.ManifestRef) (int, error)); ok {
		return returnFunc(ctx, version, updatedAt, problems, manifests)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, []domain.ProblemManifest, []domain.ManifestRef) int); ok {
		r0 = returnFunc(ctx, version, updatedAt, problems, manifests)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, []domain.ProblemManifest, []domain.ManifestRef) error); ok {
		r1 = returnFunc(ctx, version, updatedAt, problems, manifests)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIService_SyncRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncRegistry'
type MockAPIService_SyncRegistry_Call struct {
	*mock.Call
}

// SyncRegistry is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
//   - updatedAt time.Time
//   - problems []domain.ProblemManifest
//   - manifests []domain.ManifestRef
func (_e *MockAPIService_Expecter) SyncRegistry(ctx interface{}, version interface{}, updatedAt interface{}, problems interface{}, manifests interface{}) *MockAPIService_SyncRegistry_Call {
	return &MockAPIService_SyncRegistry_Call{Call: _e.mock.On("SyncRegistry", ctx, version, updatedAt, problems, manifests)}
}

func (_c *MockAPIService_SyncRegistry_Call) Run(run func(ctx context.Context, version string, updatedAt time.Time, problems []domain.ProblemManifest, manifests []domain.ManifestRef)) *MockAPIService_SyncRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 []domain.ProblemManifest
		if args[3] != nil {
			arg3 = args[3].([]domain.ProblemManifest)
		}
		var arg4 []domain.ManifestRef
		if args[4] != nil {
			arg4 = args[4].([]domain.ManifestRef)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAPIService_SyncRegistry_Call) Return(n int, err error) *MockAPIService_SyncRegistry_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAPIService_SyncRegistry_Call) RunAndReturn(run func(ctx context.Context, version string, updatedAt time.Time, problems []domain.ProblemManifest, manifests []domain.ManifestRef) (int, error)) *MockAPIService_SyncRegistry_Call {
	_c.Call.Return(run)
	return _c
}
